Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import cv2
... import os
... 
... name = input("Enter person name: ")
... 
... path = f"dataset/{name}"
... 
... os.makedirs(path, exist_ok=True)
... 
... cam = cv2.VideoCapture(0)
... 
... count = 0
... 
... while True:
...     ret, frame = cam.read()
... 
...     cv2.imshow("Capture Faces", frame)
... 
...     key = cv2.waitKey(1)
... 
...     if key == ord('s'):
...         cv2.imwrite(f"{path}/{count}.jpg", frame)
...         print("Image Saved")
...         count += 1
... 
...     elif key == ord('q'):
...         break
... 
... cam.release()
