Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import face_recognition
... import os
... import pickle
... 
... known_encodings = []
... known_names = []
... 
... dataset = "dataset"
... 
... for person in os.listdir(dataset):
... 
...     person_path = os.path.join(dataset, person)
... 
...     for image_name in os.listdir(person_path):
... 
...         image_path = os.path.join(person_path, image_name)
... 
...         image = face_recognition.load_image_file(image_path)
... 
...         encodings = face_recognition.face_encodings(image)
... 
...         if len(encodings) > 0:
...             known_encodings.append(encodings[0])
...             known_names.append(person)
... 
... data = {
...     "encodings": known_encodings,
...     "names": known_names
... }
... 
... with open("encodings.pickle", "wb") as f:
...     pickle.dump(data, f)
... 
... print("Training Complete")
